name: .NET 6.0

on:
  pull_request: {}
  push:
    branches:
      - '**'        # matches every branch

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./API/.NET 6.0
    
    steps:
    - name: Checkout ğŸ›ï¸
      uses: actions/checkout@v2
    
    - name: Setup .NET ğŸ›ï¸
      uses: actions/setup-dotnet@v1
      with:
          dotnet-version: 6.0.x
      
    - name: Install dotnet ef ğŸ”§
      run: dotnet tool install --global dotnet-ef
      
    - name: Build ğŸ§±
      run: dotnet build --configuration Release DailyToDoListAPI.sln

    - name: Test ğŸ§ª
      run: dotnet test DailyToDoListAPI.sln --configuration Release
      
