name: .NET Core 3.1

on:
  pull_request: {}
  push:
    branches:
      - '**'        # matches every branch

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./API/.Net Core 3.1
    
    steps:
    - name: Checkout ğŸ›ï¸
      uses: actions/checkout@v2
    
    - name: Setup .NET ğŸ›ï¸
      uses: actions/setup-dotnet@v1
      with:
          dotnet-version: 3.1
      
    - name: Install dotnet ef ğŸ”§
      run: dotnet tool install --global dotnet-ef
      
    - name: Build ğŸ§±
      run: dotnet build --configuration Release DailyToDoListAPI.sln

    - name: Test ğŸ§ª
      run: dotnet test DailyToDoListAPI.sln --configuration Release
      
